name: Run tests

on: push

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: install catch2
        run: |
          pwd
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          git checkout v2.x
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install
          pwd

      - name: check pwd
        run: pwd


